// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcoXilLZ_JIZ0nBw5O3EnM57VtwUM581w',
    appId: '1:638757528794:android:a720b551c5d7c06bfe31e3',
    messagingSenderId: '638757528794',
    projectId: 'kahootclone-b842c',
    storageBucket: 'kahootclone-b842c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhXns5Y-FrkRnbOR919_qhcNsshyojxQ',
    appId: '1:638757528794:ios:1266c4897c324a75fe31e3',
    messagingSenderId: '638757528794',
    projectId: 'kahootclone-b842c',
    storageBucket: 'kahootclone-b842c.firebasestorage.app',
    iosBundleId: 'edu.byu.safeScales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhXns5Y-FrkRnbOR919_qhcNsshyojxQ',
    appId: '1:638757528794:ios:1266c4897c324a75fe31e3',
    messagingSenderId: '638757528794',
    projectId: 'kahootclone-b842c',
    storageBucket: 'kahootclone-b842c.firebasestorage.app',
    iosBundleId: 'edu.byu.safeScales',
  );
}
